import React from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import './css/main.css';
import './css/ant-design.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru">
        <body className="w-100 h-100 d-flex justify-content-center flex-column">{children}</body>
        </html>
    )
}
